### ISSUE TITLE
On resize, text is redrawn but graph isn't

### ISSUE THREAD

**Issue by cbonitz** [blecher-at/gitline#1]
How to reproduce:
* Load a large repository (e.g. of the [git repo](https://github.com/git/git)) in a browser not wide enough to render every commit message in one line. Both the graph and the text will be vertically spaced accordingly.
* Make the window wide enough to show each commit message in one line

Expected:
* Text is still next to the matching nodes of the graph

Actual:
* Text is now spaced so that it fits the window width, but the graph has the old vertical spacing

**Comment by cbonitz** [comment]
Works the other way as well (make the window smaller). Tested on Chrome Version 47.0.2526.49 beta (64-bit), firefox 41.0.2 (on OS X).
![screen shot 2015-11-06 at 16 14 20](https://cloud.githubusercontent.com/assets/2099678/11000373/ad62b834-84a1-11e5-9b59-50c714534799.png)

**Comment by blecher-at** [comment]
redraw on resize implemented. thx for noticing
