### ISSUE TITLE
configuration dialog

### ISSUE THREAD

**Issue by blecher-at** [blecher-at/gitline#11]
- allow changing the config in the browser.
- store in browsers local storage

**Comment by blecher-at** [comment]
Looking for a lightweight form framework in js (for config)
Ideally i give it a typescript class and it renders UI. nothing fancy please :)

**Comment by ajgassner** [comment]
https://jqueryui.com/

**Comment by blecher-at** [comment]
jqueryui is fine with me. it is simple and dreaded for that reason, but me likes
