### ISSUE TITLE
Dereferencing of undefined when displaying git git repo

### ISSUE THREAD

**Issue by cbonitz** [blecher-at/gitline#13]
I was trying to run master on a JSON export of the git git repo, which worked fine yesterday https://github.com/cbonitz/gitline/tree/bugfix/git-repo

Undefined is dereferenced via this.commit.directparent.view.dot on line 39. As far as I can see, view is set as soon as commit.outOfScope is false in Gitline.ts. Adding filters to avoid treating nodes with outOfScope == true lets the repo render, but not correctly (see my branch)

**Comment by blecher-at** [comment]
Added your git-export to the standard examples.
