### ISSUE TITLE
Display Author/Committer

### ISSUE THREAD

**Issue by blecher-at** [blecher-at/gitline#2]
Each commit needs display of author/committer
- support avatars
- make avatars pluggable
- support rewrite of authors

**Comment by ajgassner** [comment]
Gravatar support would be nice too https://de.gravatar.com
Am 06.11.2015 8:11 nachm. schrieb Stephan <notifications@github.com>:Each commit needs display of author/committer

support avatarsmake avatars pluggablesupport rewrite of authors
