### ISSUE TITLE
Chrome rendering error:

### ISSUE THREAD

**Issue by cbonitz** [blecher-at/gitline#25]
![image](https://cloud.githubusercontent.com/assets/2099678/11020337/f2c095fa-861c-11e5-8937-963e6f025552.png)
Version 47.0.2526.35 beta-m (64-bit)

**Comment by blecher-at** [comment]
bugfix/GL-25-chrome please confirm

**Comment by cbonitz** [comment]
Fix confirmed. Thanks!
![image](https://cloud.githubusercontent.com/assets/2099678/11021747/474301ce-864c-11e5-9d55-7337a3282061.png)
